#!/usr/bin/env bash

set -euo pipefail

export PLAYWRIGHT_CLI_VERSION=$(bundle exec ruby -e 'require "playwright"; puts Playwright::COMPATIBLE_PLAYWRIGHT_VERSION.strip')
npm add -D "playwright@$PLAYWRIGHT_CLI_VERSION"
npx playwright install --with-deps chromium
